import { z } from "zod";
import { router, staffProcedure } from "./trpc";

/**
 * M10 analytics & scoring v2 — STUB router (mock data, frozen signatures).
 * READ-ONLY by contract: every procedure is a query over existing m3/m5/work
 * data; this router never writes a domain table. Wiring into appRouter is
 * orchestrator-only (root.ts). Live path swaps heuristics + LLM narrative in
 * behind env flags — no ML infra (MASTER-PLAN-V2 M10).
 */

export const analyticsRouter = router({
  /** Win-rate model over deal history (BUAF features → close probability). */
  winRate: staffProcedure
    .input(z.object({ sinceMonths: z.number().min(1).max(24).default(6) }).optional())
    .query(({ input }) => ({
      windowMonths: input?.sinceMonths ?? 6,
      dealsClosed: 42,
      dealsWon: 18,
      winRate: 0.43,
      /** Feature weights the narrative cites — mock until M10 fits the model. */
      topFactors: [
        { feature: "buaf_budget", weight: 0.31 },
        { feature: "verified_email", weight: 0.22 },
        { feature: "reply_intent_interested", weight: 0.19 },
      ],
    })),

  /** Churn signals from client activity (M4/M6 data). */
  churnRisk: staffProcedure
    .input(z.object({ limit: z.number().min(1).max(100).default(20) }).optional())
    .query(({ input }) =>
      [
        { clientId: "00000000-0000-4000-8000-0000000000a1", name: "Acme Retail", risk: 0.71, reason: "No approved deliverable in 21 days" },
        { clientId: "00000000-0000-4000-8000-0000000000b1", name: "Bright Foods", risk: 0.34, reason: "Engagement steady" },
      ].slice(0, input?.limit ?? 20),
    ),

  /** Capacity forecast from Work data (work-planning.ts). */
  capacityForecast: staffProcedure
    .input(z.object({ weeks: z.number().min(1).max(12).default(4) }).optional())
    .query(({ input }) => ({
      weeks: input?.weeks ?? 4,
      utilizationPct: 0.82,
      overbookedRoles: ["editor", "motion"],
      note: "Mock forecast — live path reads work assignments at M10",
    })),

  /** Unattended weekly agency report — LLM-written narrative over the above. */
  weeklyReport: staffProcedure
    .input(z.object({ weekOf: z.string().optional() }).optional())
    .query(({ input }) => ({
      weekOf: input?.weekOf ?? new Date().toISOString().slice(0, 10),
      pipeline: { open: 23, weightedValueAed: "412000.00" },
      capacityUtilizationPct: 0.82,
      churnRiskCount: 1,
      narrative:
        "[mock] Pipeline healthy; editor capacity tight; one client at churn risk. Live narrative generated by the analytics agent at M10.",
    })),
});
