CREATE TABLE "client" (
	"client_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_id" uuid NOT NULL,
	"name" text NOT NULL,
	"market" "market_enum" NOT NULL,
	"engagement_type" "engagement_type_enum" NOT NULL,
	"contract_value" numeric(12, 2),
	"currency" text DEFAULT 'AED' NOT NULL,
	"start_date" date,
	"renewal_date" date,
	"fee" numeric(12, 2),
	"lifecycle_status" "client_lifecycle_enum" DEFAULT 'onboarding' NOT NULL,
	"contacts" jsonb DEFAULT '{}'::jsonb,
	"approvers" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "client_deal_id_unique" UNIQUE("deal_id")
);\n\nCREATE TABLE "client_portal_user" (
	"client_portal_user_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);\n\nCREATE TABLE "connection_account" (
	"connection_account_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_employee_id" uuid,
	"owner_portal_user_id" uuid,
	"toolkit" text NOT NULL,
	"scope" text NOT NULL,
	"external_connection_id" text,
	"status" text DEFAULT 'disconnected' NOT NULL,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);\n\nCREATE TABLE "convention" (
	"convention_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rule_key" text NOT NULL,
	"version" numeric(6, 0) NOT NULL,
	"payload" jsonb NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);\n\nCREATE TABLE "deal" (
	"deal_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"sector" text,
	"stage" "deal_stage_enum" DEFAULT 'discover' NOT NULL,
	"close_outcome" "close_outcome_enum",
	"lost_reason" text,
	"lead_source_lane" "lead_source_lane_enum" NOT NULL,
	"buaf_budget" boolean,
	"buaf_urgency" boolean,
	"buaf_access" boolean,
	"buaf_fit" boolean,
	"buaf_temperature" "buaf_temperature_enum",
	"email_verified" boolean DEFAULT false NOT NULL,
	"quote_value" numeric(12, 2),
	"internal_cost" numeric(12, 2),
	"margin_pct" numeric(5, 2),
	"discount_pct" numeric(5, 2),
	"discount_approval_tier" "discount_approval_tier_enum",
	"vendor_handling_fee_pct" numeric(5, 2) DEFAULT '20.00' NOT NULL,
	"owner_employee_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);\n\nCREATE TABLE "employee" (
	"employee_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"display_name" text NOT NULL,
	"email" text NOT NULL,
	"lifecycle_status" "employee_lifecycle_enum" DEFAULT 'active' NOT NULL,
	"capacity_hours_per_week" numeric(5, 2),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "employee_email_unique" UNIQUE("email")
);\n\nCREATE TABLE "employee_auth" (
	"employee_auth_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"employee_id" uuid NOT NULL,
	"auth_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "employee_auth_employee_id_unique" UNIQUE("employee_id"),
	CONSTRAINT "employee_auth_auth_user_id_unique" UNIQUE("auth_user_id")
);