import type {
  DiscoveryDisposition,
  DiscoveryEvidenceRoute,
} from "./discovery-evidence";

export const DISCOVERY_RELEASE_QUALITY_NOW = new Date(
  "2026-09-20T00:00:00.000Z",
);

export const DISCOVERY_RELEASE_QUALITY_GATES = [
  "coverage_news_hiring_leadership_tender_import_adversarial",
  "forty_representative_cases",
  "ninety_percent_correct_classifications",
  "no_stale_undated_unsupported_admitted_as_verified",
  "awarded_parks_as_intelligence",
  "tender_not_stale_by_news_window",
  "two_distinct_tenders",
  "duplicate_identity_does_not_open_twice",
  "private_excerpt_excluded_from_packet",
  "restricted_excerpt_excluded_from_packet",
  "import_route_reuses_discovery_evaluate",
  "mock_packet_only_collectors_off",
] as const;

export type DiscoveryReleaseQualityFamily =
  | "news"
  | "hiring"
  | "leadership"
  | "tender"
  | "import"
  | "adversarial";

export type DiscoveryReleaseQualityCase = {
  id: string;
  family: DiscoveryReleaseQualityFamily;
  title: string;
  companyName: string;
  website: string;
  sourceUrl: string;
  excerpt: string;
  whyNow: string;
  eventDate?: string;
  opportunityKind:
    | "company_signal"
    | "hiring"
    | "leadership"
    | "tender"
    | "intent"
    | "submission";
  discoveryChannel:
    | "publication"
    | "hiring"
    | "leadership"
    | "intent_import"
    | "government"
    | "submission";
  visibilityScope: "public" | "restricted" | "private";
  route: DiscoveryEvidenceRoute;
  expectedDisposition: DiscoveryDisposition;
  expectedReviewState: "needs_review" | "needs_evidence" | "parked";
  expectedExcerptIncluded: boolean;
  pairWith?: string;
};

const caseOf = (
  input: DiscoveryReleaseQualityCase,
): DiscoveryReleaseQualityCase => input;

export const DISCOVERY_RELEASE_QUALITY_CASES: DiscoveryReleaseQualityCase[] = [
  caseOf({
    id: "news-fresh",
    family: "news",
    title: "Fresh dated news review",
    companyName: "RQ News Fresh",
    website: "https://campaignme.com",
    sourceUrl: "https://campaignme.com/latest/rq-news-fresh",
    excerpt: "The brand opened a regional creative review in Dubai.",
    whyNow: "A dated listing named a relevant UAE brief.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-window-edge",
    family: "news",
    title: "News on the 30-day edge stays actionable",
    companyName: "RQ News Edge",
    website: "https://gulfbusiness.com",
    sourceUrl: "https://gulfbusiness.com/latest/rq-news-edge",
    excerpt: "A hospitality group opened a communications review.",
    whyNow: "The dated article is exactly 30 days old.",
    eventDate: "2026-08-21",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-stale",
    family: "news",
    title: "News older than 30 days is stale",
    companyName: "RQ News Stale",
    website: "https://gulfnews.com",
    sourceUrl: "https://gulfnews.com/business/rq-news-stale",
    excerpt: "The group announced a creative review last quarter.",
    whyNow: "The article is 31 days old.",
    eventDate: "2026-08-20",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-very-stale",
    family: "news",
    title: "Quarter-old news is stale",
    companyName: "RQ News Old",
    website: "https://www.thenationalnews.com",
    sourceUrl: "https://www.thenationalnews.com/business/rq-news-old",
    excerpt: "The issuer discussed a review in June.",
    whyNow: "The listing is far outside the news window.",
    eventDate: "2026-06-01",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-undated",
    family: "news",
    title: "Undated news needs evidence",
    companyName: "RQ News Undated",
    website: "https://www.arabianbusiness.com",
    sourceUrl: "https://www.arabianbusiness.com/industries/rq-news-undated",
    excerpt: "A retailer is said to be reviewing agencies.",
    whyNow: "No source date was published.",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-awarded",
    family: "news",
    title: "Awarded agency win parks as intelligence",
    companyName: "RQ News Awarded",
    website: "https://communicateonline.me",
    sourceUrl: "https://communicateonline.me/news/rq-news-awarded",
    excerpt: "The issuer awarded the account to another agency last week.",
    whyNow: "Already-awarded appointment is intelligence, not an open pitch.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "awarded",
    expectedReviewState: "parked",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-unsupported",
    family: "news",
    title: "Ungrounded buyer-certainty claim is unsupported",
    companyName: "RQ News Unsupported",
    website: "https://www.khaleejtimes.com",
    sourceUrl: "https://www.khaleejtimes.com/business/rq-news-unsupported",
    excerpt: "The brand opened a regional review in Dubai.",
    whyNow: "Buyer has approved AED 400000",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "unsupported",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-grounded-certainty",
    family: "news",
    title: "Excerpt-grounded certainty stays actionable",
    companyName: "RQ News Grounded",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-news-grounded",
    excerpt: "The buyer has approved AED 400000 for a Dubai review.",
    whyNow: "Buyer has approved AED 400000",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-future-date",
    family: "news",
    title: "Future event date is not verified",
    companyName: "RQ News Future",
    website: "https://campaignme.com",
    sourceUrl: "https://campaignme.com/latest/rq-news-future",
    excerpt: "A listing names a review that has not happened yet.",
    whyNow: "The printed date is in the future.",
    eventDate: "2026-10-01",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "needs_evidence",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "news-private",
    family: "news",
    title: "Private news excerpt stays out of the packet",
    companyName: "RQ News Private",
    website: "https://campaignme.com",
    sourceUrl: "https://campaignme.com/latest/rq-news-private",
    excerpt: "Confidential mailbox excerpt that must not enter the packet.",
    whyNow: "A dated listing named a relevant UAE brief.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "private",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: false,
  }),
  caseOf({
    id: "hiring-fresh",
    family: "hiring",
    title: "Fresh hiring listing",
    companyName: "RQ Hiring Fresh",
    website: "https://gulfbusiness.com",
    sourceUrl: "https://gulfbusiness.com/jobs/rq-hiring-fresh",
    excerpt: "The company posted a UAE marketing director vacancy.",
    whyNow: "A dated job listing named hospitality work.",
    eventDate: "2026-09-13",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-window-edge",
    family: "hiring",
    title: "Hiring on the 14-day edge stays actionable",
    companyName: "RQ Hiring Edge",
    website: "https://gulfnews.com",
    sourceUrl: "https://gulfnews.com/business/rq-hiring-edge",
    excerpt: "A brand-marketing vacancy is still listed in Dubai.",
    whyNow: "The listing is exactly 14 days old.",
    eventDate: "2026-09-06",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-stale",
    family: "hiring",
    title: "Hiring older than 14 days is stale",
    companyName: "RQ Hiring Stale",
    website: "https://www.arabianbusiness.com",
    sourceUrl: "https://www.arabianbusiness.com/jobs/rq-hiring-stale",
    excerpt: "The vacancy was posted last month.",
    whyNow: "The listing is 15 days old.",
    eventDate: "2026-09-05",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-undated",
    family: "hiring",
    title: "Undated hiring needs evidence",
    companyName: "RQ Hiring Undated",
    website: "https://www.thenationalnews.com",
    sourceUrl: "https://www.thenationalnews.com/jobs/rq-hiring-undated",
    excerpt: "A marketing vacancy is mentioned without a date.",
    whyNow: "The listing has no published date.",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-awarded",
    family: "hiring",
    title: "Awarded hiring copy parks",
    companyName: "RQ Hiring Awarded",
    website: "https://communicateonline.me",
    sourceUrl: "https://communicateonline.me/jobs/rq-hiring-awarded",
    excerpt: "The issuer appointed another agency and is hiring for delivery.",
    whyNow: "This is an already-awarded appointment, not an open pitch.",
    eventDate: "2026-09-13",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "awarded",
    expectedReviewState: "parked",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-unsupported",
    family: "hiring",
    title: "Hiring with invented buyer certainty is unsupported",
    companyName: "RQ Hiring Unsupported",
    website: "https://www.khaleejtimes.com",
    sourceUrl: "https://www.khaleejtimes.com/jobs/rq-hiring-unsupported",
    excerpt: "The company posted a UAE marketing vacancy.",
    whyNow: "Confirmed intent to hire our agency immediately",
    eventDate: "2026-09-13",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "unsupported",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "hiring-private",
    family: "hiring",
    title: "Private hiring excerpt stays out of the packet",
    companyName: "RQ Hiring Private",
    website: "https://gulfbusiness.com",
    sourceUrl: "https://gulfbusiness.com/jobs/rq-hiring-private",
    excerpt: "Private recruiter note that must not enter the packet.",
    whyNow: "A dated job listing named hospitality work.",
    eventDate: "2026-09-13",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "private",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: false,
  }),
  caseOf({
    id: "hiring-restricted",
    family: "hiring",
    title: "Restricted hiring excerpt stays out of the packet",
    companyName: "RQ Hiring Restricted",
    website: "https://gulfnews.com",
    sourceUrl: "https://gulfnews.com/business/rq-hiring-restricted",
    excerpt: "Restricted workspace note that must not enter the packet.",
    whyNow: "A dated job listing named hospitality work.",
    eventDate: "2026-09-13",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "restricted",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: false,
  }),
  caseOf({
    id: "leadership-fresh",
    family: "leadership",
    title: "Fresh leadership change",
    companyName: "RQ Leadership Fresh",
    website: "https://www.arabianbusiness.com",
    sourceUrl: "https://www.arabianbusiness.com/leadership/rq-fresh",
    excerpt: "The retailer named a new chief marketing officer in Dubai.",
    whyNow: "A dated leadership change is relevant to brand work.",
    eventDate: "2026-08-01",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "leadership-window-edge",
    family: "leadership",
    title: "Leadership on the 90-day edge stays actionable",
    companyName: "RQ Leadership Edge",
    website: "https://www.thenationalnews.com",
    sourceUrl: "https://www.thenationalnews.com/business/rq-leadership-edge",
    excerpt: "A hotel group named a new brand director.",
    whyNow: "The announcement is exactly 90 days old.",
    eventDate: "2026-06-22",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "leadership-stale",
    family: "leadership",
    title: "Leadership older than 90 days is stale",
    companyName: "RQ Leadership Stale",
    website: "https://campaignme.com",
    sourceUrl: "https://campaignme.com/latest/rq-leadership-stale",
    excerpt: "The group named a new marketing lead last spring.",
    whyNow: "The announcement is 91 days old.",
    eventDate: "2026-06-21",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "leadership-undated",
    family: "leadership",
    title: "Undated leadership needs evidence",
    companyName: "RQ Leadership Undated",
    website: "https://communicateonline.me",
    sourceUrl: "https://communicateonline.me/news/rq-leadership-undated",
    excerpt: "A new marketing lead was mentioned without a date.",
    whyNow: "The article has no published date.",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "leadership-awarded",
    family: "leadership",
    title: "Awarded leadership item parks",
    companyName: "RQ Leadership Awarded",
    website: "https://gulfbusiness.com",
    sourceUrl: "https://gulfbusiness.com/latest/rq-leadership-awarded",
    excerpt: "The issuer won the pitch and named a new client lead.",
    whyNow: "This is already-awarded work, not an open pitch.",
    eventDate: "2026-08-01",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "awarded",
    expectedReviewState: "parked",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "leadership-unsupported",
    family: "leadership",
    title: "Leadership with invented authority is unsupported",
    companyName: "RQ Leadership Unsupported",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-leadership-unsupported",
    excerpt: "The retailer named a new chief marketing officer in Dubai.",
    whyNow: "Confirmed authority to buy immediately",
    eventDate: "2026-08-01",
    opportunityKind: "leadership",
    discoveryChannel: "leadership",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "unsupported",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "tender-old-still-open",
    family: "tender",
    title: "Old open tender is not stale by the 30-day news rule",
    companyName: "RQ Tender One",
    website: "https://www.rta.ae",
    sourceUrl: "https://www.rta.ae/wps/portal/tender-one",
    excerpt: "The authority published an open creative services tender.",
    whyNow: "Open government tender still has a deadline.",
    eventDate: "2020-01-01",
    opportunityKind: "tender",
    discoveryChannel: "government",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "tender-two-distinct",
    family: "tender",
    title: "Second distinct tender stays a separate case",
    companyName: "RQ Tender Two",
    website: "https://www.rta.ae",
    sourceUrl: "https://www.rta.ae/wps/portal/tender-two",
    excerpt: "A second media-services tender is open with its own deadline.",
    whyNow: "This is a different tender from the first listing.",
    eventDate: "2021-06-15",
    opportunityKind: "tender",
    discoveryChannel: "government",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "tender-undated",
    family: "tender",
    title: "Undated tender needs evidence",
    companyName: "RQ Tender Undated",
    website: "https://www.rta.ae",
    sourceUrl: "https://www.rta.ae/wps/portal/tender-undated",
    excerpt: "A government brief is mentioned without a deadline date.",
    whyNow: "The notice has no published date.",
    opportunityKind: "tender",
    discoveryChannel: "government",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "tender-awarded",
    family: "tender",
    title: "Awarded tender parks",
    companyName: "RQ Tender Awarded",
    website: "https://www.rta.ae",
    sourceUrl: "https://www.rta.ae/wps/portal/tender-awarded",
    excerpt: "The authority awarded the creative services tender last month.",
    whyNow: "Already-awarded government work is intelligence.",
    eventDate: "2024-03-01",
    opportunityKind: "tender",
    discoveryChannel: "government",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "awarded",
    expectedReviewState: "parked",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "tender-unsupported",
    family: "tender",
    title: "Tender with invented budget is unsupported",
    companyName: "RQ Tender Unsupported",
    website: "https://www.rta.ae",
    sourceUrl: "https://www.rta.ae/wps/portal/tender-unsupported",
    excerpt: "The authority published an open creative services tender.",
    whyNow: "Buyer has approved AED 900000",
    eventDate: "2024-03-01",
    opportunityKind: "tender",
    discoveryChannel: "government",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "unsupported",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "import-fresh",
    family: "import",
    title: "Dated intent import is actionable",
    companyName: "RQ Import Fresh",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-import-fresh",
    excerpt: "The imported row names a dated Dubai review.",
    whyNow: "Intent import carried a source date.",
    eventDate: "2026-09-17",
    opportunityKind: "intent",
    discoveryChannel: "intent_import",
    visibilityScope: "public",
    route: "import",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "import-undated",
    family: "import",
    title: "Undated intent import needs evidence",
    companyName: "RQ Import Undated",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-import-undated",
    excerpt: "The imported row names a review without a date.",
    whyNow: "Intent import omitted the source date.",
    opportunityKind: "intent",
    discoveryChannel: "intent_import",
    visibilityScope: "public",
    route: "import",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "import-stale",
    family: "import",
    title: "Stale intent import needs evidence",
    companyName: "RQ Import Stale",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-import-stale",
    excerpt: "The imported row names an old review.",
    whyNow: "The import date is outside the news window.",
    eventDate: "2026-07-01",
    opportunityKind: "intent",
    discoveryChannel: "intent_import",
    visibilityScope: "public",
    route: "import",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "import-private",
    family: "import",
    title: "Private import excerpt stays out of the packet",
    companyName: "RQ Import Private",
    website: "https://www.timeoutdubai.com",
    sourceUrl: "https://www.timeoutdubai.com/news/rq-import-private",
    excerpt: "Private import excerpt that must not enter the packet.",
    whyNow: "Intent import carried a source date.",
    eventDate: "2026-09-17",
    opportunityKind: "intent",
    discoveryChannel: "intent_import",
    visibilityScope: "private",
    route: "import",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: false,
  }),
  caseOf({
    id: "adversarial-duplicate-a",
    family: "adversarial",
    title: "First copy of a duplicate opportunity",
    companyName: "RQ Duplicate Signal",
    website: "https://gulfnews.com",
    sourceUrl: "https://gulfnews.com/business/rq-duplicate",
    excerpt: "The brand opened a regional creative review in Dubai.",
    whyNow: "Same opportunity key must not open twice.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
    pairWith: "adversarial-duplicate-b",
  }),
  caseOf({
    id: "adversarial-duplicate-b",
    family: "adversarial",
    title: "Replay of the same opportunity is a duplicate",
    companyName: "RQ Duplicate Signal",
    website: "https://gulfnews.com",
    sourceUrl: "https://gulfnews.com/business/rq-duplicate",
    excerpt: "The brand opened a regional creative review in Dubai.",
    whyNow: "Same opportunity key must not open twice.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "duplicate",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: true,
    pairWith: "adversarial-duplicate-a",
  }),
  caseOf({
    id: "adversarial-homepage",
    family: "adversarial",
    title: "Homepage copy without a date is undated",
    companyName: "RQ Homepage",
    website: "https://campaignme.com",
    sourceUrl: "https://campaignme.com/",
    excerpt: "Welcome to our homepage. We make brands famous.",
    whyNow: "The page has no dated opportunity.",
    opportunityKind: "submission",
    discoveryChannel: "submission",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "adversarial-will-buy",
    family: "adversarial",
    title: "Will-buy claim without excerpt support is unsupported",
    companyName: "RQ Will Buy",
    website: "https://gulfbusiness.com",
    sourceUrl: "https://gulfbusiness.com/latest/rq-will-buy",
    excerpt: "The brand opened a regional review in Dubai.",
    whyNow: "They will buy this week without any cited budget.",
    eventDate: "2026-09-18",
    opportunityKind: "submission",
    discoveryChannel: "submission",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "unsupported",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "adversarial-invalid-date",
    family: "adversarial",
    title: "Unparseable date is treated as missing",
    companyName: "RQ Invalid Date",
    website: "https://www.arabianbusiness.com",
    sourceUrl: "https://www.arabianbusiness.com/industries/rq-invalid-date",
    excerpt: "A listing names a review with a prose date only.",
    whyNow: "Last Tuesday is not a verified source date.",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "undated",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "adversarial-agency-of-record",
    family: "adversarial",
    title: "Agency-of-record win parks",
    companyName: "RQ AOR",
    website: "https://communicateonline.me",
    sourceUrl: "https://communicateonline.me/news/rq-aor",
    excerpt: "The issuer named a new agency of record for the region.",
    whyNow: "This is an appointment, not an open pitch.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "awarded",
    expectedReviewState: "parked",
    expectedExcerptIncluded: true,
  }),
  caseOf({
    id: "adversarial-restricted-news",
    family: "adversarial",
    title: "Restricted news excerpt stays out of the packet",
    companyName: "RQ Restricted News",
    website: "https://www.thenationalnews.com",
    sourceUrl: "https://www.thenationalnews.com/business/rq-restricted",
    excerpt: "Restricted workspace excerpt that must not enter the packet.",
    whyNow: "A dated listing named a relevant UAE brief.",
    eventDate: "2026-09-18",
    opportunityKind: "company_signal",
    discoveryChannel: "publication",
    visibilityScope: "restricted",
    route: "manual",
    expectedDisposition: "actionable",
    expectedReviewState: "needs_review",
    expectedExcerptIncluded: false,
  }),
  caseOf({
    id: "adversarial-stale-hiring-not-verified",
    family: "adversarial",
    title: "Stale hiring cannot be admitted as verified",
    companyName: "RQ Stale Hiring Gate",
    website: "https://www.khaleejtimes.com",
    sourceUrl: "https://www.khaleejtimes.com/jobs/rq-stale-hiring-gate",
    excerpt: "An old vacancy is still visible on the careers page.",
    whyNow: "The listing is far outside the hiring window.",
    eventDate: "2026-07-01",
    opportunityKind: "hiring",
    discoveryChannel: "hiring",
    visibilityScope: "public",
    route: "manual",
    expectedDisposition: "stale",
    expectedReviewState: "needs_evidence",
    expectedExcerptIncluded: true,
  }),
];

export function discoveryReleaseQualityCoverage() {
  const families = new Set(
    DISCOVERY_RELEASE_QUALITY_CASES.map((item) => item.family),
  );
  return {
    caseCount: DISCOVERY_RELEASE_QUALITY_CASES.length,
    families: [...families],
  };
}
