export type FeatureSource = "native" | "bayzat" | "asana" | "integration";

export type FeatureAvailability = "available" | "beta" | "planned";

export type FeatureDefinition = {
  key: string;
  name: string;
  description: string;
  group: string;
  source: FeatureSource;
  availability: FeatureAvailability;
  defaultEnabled: boolean;
  route?: string;
  /** Essential recovery surfaces cannot be disabled. */
  protected?: boolean;
};

const feature = (definition: FeatureDefinition): FeatureDefinition =>
  definition;

/**
 * Code-owned feature catalogue. Adding one entry makes a feature appear in
 * Feature Lab automatically; the database stores only tenant/access overrides.
 */
export const FEATURE_CATALOG: readonly FeatureDefinition[] = [
  feature({
    key: "core.home",
    name: "Home",
    description: "Staff landing page and workspace overview.",
    group: "Core",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/",
    protected: true,
  }),
  feature({
    key: "crm.workspace",
    name: "CRM",
    description:
      "Companies, contacts, deals, activities, outreach, and quotes.",
    group: "CRM",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/crm",
  }),
  feature({
    key: "delivery.workspace",
    name: "Delivery",
    description: "Briefs, production tasks, calendars, assets, and approvals.",
    group: "Delivery",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/delivery",
  }),
  feature({
    key: "finance.workspace",
    name: "Finance",
    description: "Billing, invoices, VAT, margin, and finance workflows.",
    group: "Finance",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/finance",
  }),
  feature({
    key: "people.core_hr",
    name: "Core HR",
    description:
      "Employee directory, profiles, documents, and lifecycle operations.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/people",
  }),
  feature({
    key: "people.leave_attendance",
    name: "Leave & attendance",
    description:
      "Leave policies, requests, balances, attendance, and corrections.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/time",
  }),
  feature({
    key: "people.talent",
    name: "Talent",
    description:
      "Recruitment, requisitions, candidates, onboarding, and performance.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/talent",
  }),
  feature({
    key: "people.payroll",
    name: "Payroll",
    description:
      "Payroll preparation, approval, WPS handoff, and finance posting.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/workforce-payroll",
  }),
  feature({
    key: "people.shifts_timesheets",
    name: "Shifts & timesheets",
    description: "Schedules, shifts, time entries, and approvals.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/work-schedule",
  }),
  feature({
    key: "people.workplace",
    name: "Workplace",
    description: "Expenses, travel, letters, assets, and workplace services.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/workplace",
  }),
  feature({
    key: "people.benefits",
    name: "Benefits",
    description: "Benefits, insurance enrolments, claims, and reporting.",
    group: "People",
    source: "bayzat",
    availability: "available",
    defaultEnabled: true,
    route: "/benefits",
  }),
  feature({
    key: "people.digital_cards",
    name: "Digital cards",
    description: "Employee digital identity and shareable profile cards.",
    group: "People",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/my-card",
  }),
  feature({
    key: "requests.feature_intake",
    name: "Feature requests",
    description: "Idea and voice intake, PRDs, approval, and build tracking.",
    group: "Core",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/requests",
  }),
  feature({
    key: "support.tickets",
    name: "Support tickets",
    description:
      "Employee and client support requests with triage and SLA tracking.",
    group: "Core",
    source: "native",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "analytics.dashboards",
    name: "Dashboards",
    description: "Operational, HR, finance, delivery, and governed reporting.",
    group: "Analytics",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/dashboards",
  }),
  feature({
    key: "ai.custom_apps",
    name: "AI custom apps",
    description: "Governed no-code apps and natural-language reports.",
    group: "AI",
    source: "native",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "automation.n8n",
    name: "Automation",
    description: "Human-approved workflow proposals and n8n execution.",
    group: "Automation",
    source: "integration",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "portal.client",
    name: "Client portal",
    description:
      "Client deliveries, approvals, and reports with tenant isolation.",
    group: "Portal",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/portal",
  }),
  feature({
    key: "integrations.connections",
    name: "Connections",
    description: "Managed OAuth and API-key connections.",
    group: "Admin & Security",
    source: "integration",
    availability: "available",
    defaultEnabled: true,
    route: "/settings/connections",
  }),
  feature({
    key: "admin.roles",
    name: "Roles & permissions",
    description: "Role-based permission policies and access review.",
    group: "Admin & Security",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/roles",
  }),
  feature({
    key: "admin.audit",
    name: "Audit log",
    description: "Append-only security and business-action audit trail.",
    group: "Admin & Security",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/admin/audit",
  }),
  feature({
    key: "admin.feature_lab",
    name: "Feature Lab",
    description: "Global, client, role, and user feature controls.",
    group: "Admin & Security",
    source: "native",
    availability: "available",
    defaultEnabled: true,
    route: "/admin/features",
    protected: true,
  }),

  // Asana-compatible work management foundation.
  feature({
    key: "work.projects",
    name: "Projects",
    description:
      "Shared project hubs for initiatives, programs, and recurring processes.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
    route: "/work",
  }),
  feature({
    key: "work.tasks",
    name: "Tasks",
    description:
      "Owned work with descriptions, dates, priority, completion, and activity.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
    route: "/work",
  }),
  feature({
    key: "work.subtasks",
    name: "Subtasks",
    description: "Nested work items for breaking down larger tasks.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.assignees",
    name: "Task assignees",
    description: "One accountable owner per task with reassignment history.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.sections",
    name: "Sections & columns",
    description: "Ordered workflow stages shared by list and board views.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.dates",
    name: "Start dates, due dates & times",
    description: "Date and time scheduling with timezone-safe deadlines.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.dependencies",
    name: "Dependencies",
    description: "Blocking and blocked-by links between work items.",
    group: "Work management",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.comments",
    name: "Comments & mentions",
    description: "Task discussions, mentions, edits, and activity history.",
    group: "Communication",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.followers",
    name: "Task followers",
    description: "Follow tasks and receive permission-aware Inbox updates.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.custom_fields",
    name: "Custom fields",
    description: "Reusable typed fields for consistent work metadata.",
    group: "Work management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.tags",
    name: "Tags",
    description: "Cross-project labels for filtering and reporting.",
    group: "Work management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.multi_home",
    name: "Multi-home tasks",
    description: "One task shown in multiple projects without duplication.",
    group: "Work management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.recurring_tasks",
    name: "Recurring tasks",
    description: "Scheduled task recurrence with future occurrence generation.",
    group: "Work management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.attachments",
    name: "Attachments",
    description: "Files and external links attached to tasks and messages.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.likes",
    name: "Likes",
    description:
      "Lightweight acknowledgement for tasks, comments, and updates.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.proofing",
    name: "Proofing",
    description:
      "Pinned image and PDF feedback that can become actionable tasks.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.project_messages",
    name: "Project & team messages",
    description:
      "Announcements and project conversations outside individual tasks.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.team_message_permissions",
    name: "Team message send permissions",
    description:
      "Choose whether all team members or only team admins may send messages.",
    group: "Communication",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.rich_text",
    name: "Rich text",
    description: "Structured text, lists, links, mentions, and formatting.",
    group: "Communication",
    source: "asana",
    availability: "planned",
    defaultEnabled: false,
  }),
  feature({
    key: "work.forms",
    name: "Forms",
    description: "Configurable work intake that creates tasks in a project.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.rules",
    name: "Rules",
    description: "Trigger, condition, branch, and action workflow automation.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.rules.scheduled",
    name: "Scheduled rules",
    description:
      "Run project rules on a governed recurring cadence without a task event.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.rules.collaborator_trigger",
    name: "Collaborator-added rules",
    description:
      "Trigger project rules when a collaborator is added to a task.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.templates",
    name: "Project & task templates",
    description:
      "Reusable project structures and task defaults with relative dates.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.bundles",
    name: "Bundles",
    description:
      "Versioned packages of sections, fields, rules, and templates applied at scale.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.approvals",
    name: "Approvals",
    description: "Request, approve, reject, or request changes on work.",
    group: "Workflows",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.milestones",
    name: "Milestones",
    description: "Key project markers represented by milestone work items.",
    group: "Work management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.time_tracking",
    name: "Time tracking",
    description: "Estimated and actual time entries with timers and reporting.",
    group: "Resource management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),

  // Views and personal productivity.
  feature({
    key: "work.views.list",
    name: "List view",
    description: "Sortable, filterable grid view of project tasks.",
    group: "Views",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.views.board",
    name: "Board view",
    description: "Kanban columns backed by the same sections and tasks.",
    group: "Views",
    source: "asana",
    availability: "available",
    defaultEnabled: true,
  }),
  feature({
    key: "work.views.calendar",
    name: "Calendar view",
    description: "Project tasks placed on a monthly calendar by due date.",
    group: "Views",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.views.timeline",
    name: "Timeline view",
    description:
      "Project tasks placed across a horizontal date-range timeline.",
    group: "Views",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.views.gantt",
    name: "Gantt view",
    description:
      "Baseline, critical path, dependencies, and schedule variance.",
    group: "Views",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.views.files",
    name: "Files view",
    description: "Gallery of files attached across a project.",
    group: "Views",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.my_tasks",
    name: "My tasks",
    description:
      "Personal assignment hub with filtering and completion controls.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.inbox",
    name: "Inbox",
    description:
      "Followed-work notifications, filters, triage, and read state.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.inbox.message_status_filters",
    name: "Message & status Inbox filters",
    description:
      "Filter Inbox updates between task activity, messages, and status updates.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.search",
    name: "Search",
    description: "Permission-aware work search with task and project filters.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.saved_searches",
    name: "Saved searches",
    description: "Reusable search criteria for repeated review and analysis.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.out_of_office",
    name: "Out of office",
    description:
      "Availability windows that inform assignments and collaboration.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.accessibility",
    name: "Accessibility preferences",
    description:
      "Keyboard operation, reduced motion, and color-safe presentation.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.mobile_pwa",
    name: "Mobile & installable app",
    description:
      "Responsive, installable experience with offline-safe navigation.",
    group: "Personal productivity",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),

  // Goals, planning, reporting, and capacity.
  feature({
    key: "work.goals",
    name: "Goals",
    description:
      "Company, team, and individual goals linked to contributing work.",
    group: "Goals & reporting",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.portfolios",
    name: "Portfolios",
    description:
      "Strategic collections of projects with health and progress roll-ups.",
    group: "Goals & reporting",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.status_updates",
    name: "Status updates",
    description:
      "Structured project, portfolio, and goal progress communication.",
    group: "Goals & reporting",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.reporting_dashboards",
    name: "Reporting dashboards",
    description: "Real-time charts, filters, drill-down, and exports.",
    group: "Goals & reporting",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.workload",
    name: "Workload",
    description: "Capacity planning and allocation across people and projects.",
    group: "Resource management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.capacity_planning",
    name: "Capacity planning",
    description: "Role and person allocation across longer planning horizons.",
    group: "Resource management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.budgets",
    name: "Budgets & cost fields",
    description: "Project budgets, rates, spend, and forecast variance.",
    group: "Resource management",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),

  // Organization, governance, and enterprise controls.
  feature({
    key: "work.teams",
    name: "Teams",
    description:
      "Team membership, privacy, shared projects, and inherited project access.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.guests",
    name: "Guests",
    description: "External collaborators restricted to explicitly shared work.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.view_only",
    name: "View-only access",
    description: "Read-only participation at workspace and object levels.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.object_permissions",
    name: "Project & object permissions",
    description: "Object-level admins, editors, commenters, and viewers.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.custom_rbac",
    name: "Custom RBAC",
    description: "Configurable member, guest, and admin permissions.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.admin_console",
    name: "Organization admin console",
    description:
      "Members, guests, domains, apps, defaults, and security policy.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
    route: "/admin/work",
  }),
  feature({
    key: "work.sso_scim",
    name: "SSO & SCIM",
    description: "Enterprise authentication and automated user provisioning.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.audit_export",
    name: "Audit log & SIEM export",
    description: "Immutable security events and compliance export.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.domain_controls",
    name: "Domain-wide defaults",
    description: "Organization-level project defaults and sharing controls.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.sandboxes",
    name: "Sandboxes",
    description:
      "Isolated environments for testing workflows and administration.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.data_export",
    name: "Import, export & backup",
    description:
      "Asana import, reporting CSV, audit export, and full Work graph backup.",
    group: "Admin & Security",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),

  // Migration and integrations.
  feature({
    key: "asana.connection",
    name: "Asana connection",
    description:
      "OAuth connection to an Asana workspace through a live provider.",
    group: "Integrations",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "asana.import",
    name: "Asana import",
    description:
      "Read-only discovery and idempotent import of projects, tasks, comments, files, and relationships.",
    group: "Integrations",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "asana.sync",
    name: "Asana incremental sync",
    description:
      "Cursor-based change detection with idempotent reconciliation during cutover.",
    group: "Integrations",
    source: "asana",
    availability: "beta",
    defaultEnabled: true,
  }),
  feature({
    key: "work.integrations.files",
    name: "Cloud file integrations",
    description: "Google Drive, OneDrive, Dropbox, Box, and Adobe assets.",
    group: "Integrations",
    source: "asana",
    availability: "planned",
    defaultEnabled: false,
  }),
  feature({
    key: "work.integrations.communication",
    name: "Communication integrations",
    description: "Email, Slack, Teams, and Zoom work capture and updates.",
    group: "Integrations",
    source: "asana",
    availability: "planned",
    defaultEnabled: false,
  }),
  feature({
    key: "work.integrations.enterprise",
    name: "Enterprise integrations",
    description:
      "Salesforce, Jira, Power BI, and service-management workflows.",
    group: "Integrations",
    source: "asana",
    availability: "planned",
    defaultEnabled: false,
  }),
  feature({
    key: "work.api_webhooks",
    name: "API, webhooks & app components",
    description: "Public automation surface with signed event delivery.",
    group: "Integrations",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),

  // Asana-compatible AI surface, including the 2026 releases.
  feature({
    key: "work.ai.smart_chat",
    name: "Smart chat",
    description:
      "Permission-aware questions, answers, insights, and task creation across work.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_summaries",
    name: "Smart summaries",
    description:
      "Task, project, portfolio, and inbox summaries with action extraction.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_status",
    name: "Smart status",
    description:
      "Draft project, portfolio, and goal updates from live work context.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_fields",
    name: "Smart fields",
    description:
      "AI-generated field definitions and permission-safe field completion.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_editor",
    name: "Smart editor",
    description:
      "Rewrite, shorten, expand, format, and adjust tone with review before save.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_goals",
    name: "Smart goals",
    description:
      "Goal drafting, improvement recommendations, and progress insights.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_projects",
    name: "Smart projects",
    description:
      "Generate project descriptions, sections, and fields from an objective.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.smart_rules",
    name: "Smart rule creator",
    description:
      "Generate editable workflow rules from natural-language instructions.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.risk_reports",
    name: "AI risk reports",
    description:
      "Recurring blocker, slippage, and mitigation analysis linked to source work.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.studio",
    name: "AI Studio",
    description:
      "No-code AI workflow builder for checking, classifying, routing, acting, and reporting.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.teammates",
    name: "AI Teammates",
    description:
      "Shareable collaborative agents that work through tasks and comments.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.teammate_skills",
    name: "AI Teammate skills",
    description:
      "Reusable instructions, trigger conditions, and reference attachments.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.teammate_memory",
    name: "AI Teammate memory & access",
    description:
      "Governed agent memory, work access, integrations, and approvals.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.dash",
    name: "AI Chief of Staff",
    description:
      "Daily brief, priority surfacing, blockers, decisions, and recommended actions.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
  feature({
    key: "work.ai.connectors",
    name: "AI connectors & MCP",
    description:
      "Permission-aware AI access to connected work and external tools.",
    group: "AI",
    source: "asana",
    availability: "beta",
    defaultEnabled: false,
  }),
];

export const FEATURE_BY_KEY = new Map(
  FEATURE_CATALOG.map((item) => [item.key, item]),
);

const PAGE_FEATURES: readonly [prefix: string, featureKey: string][] = [
  ["/admin/features", "admin.feature_lab"],
  ["/admin/work", "work.admin_console"],
  ["/admin/audit", "admin.audit"],
  ["/settings/asana-migration", "asana.connection"],
  ["/settings/connections", "integrations.connections"],
  ["/roles", "admin.roles"],
  ["/workforce-payroll", "people.payroll"],
  ["/work-schedule", "people.shifts_timesheets"],
  ["/workplace", "people.workplace"],
  ["/benefits", "people.benefits"],
  ["/talent", "people.talent"],
  ["/time", "people.leave_attendance"],
  ["/people", "people.core_hr"],
  ["/hr", "people.core_hr"],
  ["/payroll", "people.payroll"],
  ["/my-card", "people.digital_cards"],
  ["/work/my-tasks", "work.my_tasks"],
  ["/work/inbox", "work.inbox"],
  ["/work/messages", "work.project_messages"],
  ["/work/search", "work.search"],
  ["/work/planning", "work.projects"],
  ["/work/ai/studio", "work.ai.studio"],
  ["/work/ai/teammates", "work.ai.teammates"],
  ["/work", "work.projects"],
  ["/portal/work", "work.guests"],
  ["/crm", "crm.workspace"],
  ["/sales", "crm.workspace"],
  ["/delivery", "delivery.workspace"],
  ["/traffic", "delivery.workspace"],
  ["/creative", "delivery.workspace"],
  ["/account", "delivery.workspace"],
  ["/assets", "delivery.workspace"],
  ["/finance", "finance.workspace"],
  ["/billing", "finance.workspace"],
  ["/margin", "finance.workspace"],
  ["/requests", "requests.feature_intake"],
  ["/dashboards", "analytics.dashboards"],
  ["/portal", "portal.client"],
  ["/", "core.home"],
];

export function featureForPathname(pathname: string): string | null {
  for (const [prefix, featureKey] of PAGE_FEATURES) {
    if (
      pathname === prefix ||
      (prefix !== "/" && pathname.startsWith(`${prefix}/`))
    ) {
      return featureKey;
    }
  }
  return null;
}

const API_FEATURES: readonly [prefix: string, featureKey: string][] = [
  ["admin.features.", "admin.feature_lab"],
  ["admin.audit.", "admin.audit"],
  ["admin.roles.", "admin.roles"],
  ["admin.permissions.", "admin.roles"],
  ["connections.asanaStatus", "asana.connection"],
  ["connections.", "integrations.connections"],
  ["asanaMigration.import", "asana.import"],
  ["asanaMigration.dryRun", "asana.import"],
  ["asanaMigration.sync", "asana.sync"],
  ["asanaMigration.", "asana.connection"],
  ["workAdmin.teams.setMessagePermission", "work.team_message_permissions"],
  ["workAdmin.teams.", "work.teams"],
  ["workAdmin.guests.", "work.guests"],
  ["workAdmin.members.", "work.view_only"],
  ["workAdmin.policy.", "work.domain_controls"],
  ["workAdmin.rbac.", "work.custom_rbac"],
  ["workAdmin.identity.", "work.sso_scim"],
  ["workAdmin.apiWebhooks.", "work.api_webhooks"],
  ["workAdmin.sandboxes.", "work.sandboxes"],
  ["workAdmin.export.audit", "work.audit_export"],
  ["workAdmin.export.organization", "work.data_export"],
  ["workAdmin.", "work.admin_console"],
  ["workAiStudio.", "work.ai.studio"],
  ["workAiTeammates.skills.", "work.ai.teammate_skills"],
  ["workAiTeammates.memory.", "work.ai.teammate_memory"],
  ["workAiTeammates.", "work.ai.teammates"],
  ["featureRequests.", "requests.feature_intake"],
  ["coreHr.", "people.core_hr"],
  ["hrOperations.", "people.leave_attendance"],
  ["talent.", "people.talent"],
  ["workforcePayroll.", "people.payroll"],
  ["payroll.", "people.payroll"],
  ["workplace.", "people.workplace"],
  ["shiftsTimesheets.", "people.shifts_timesheets"],
  ["benefits.", "people.benefits"],
  ["digitalCards.", "people.digital_cards"],
  ["aiCustomApps.", "ai.custom_apps"],
  ["tickets.", "support.tickets"],
  ["automation.", "automation.n8n"],
  ["work.projects.", "work.projects"],
  ["work.sections.", "work.sections"],
  ["work.tasks.", "work.tasks"],
  ["work.comments.", "work.comments"],
  ["work.dependencies.", "work.dependencies"],
  ["work.followers.", "work.followers"],
  ["work.messages.", "work.project_messages"],
  ["work.likes.", "work.likes"],
  ["work.proofing.", "work.proofing"],
  ["work.outOfOffice.", "work.out_of_office"],
  ["work.accessibility.", "work.accessibility"],
  ["work.tags.", "work.tags"],
  ["work.customFields.", "work.custom_fields"],
  ["work.attachments.", "work.attachments"],
  ["work.recurrence.", "work.recurring_tasks"],
  ["work.personal.myTasks", "work.my_tasks"],
  ["work.personal.inbox", "work.inbox"],
  ["work.personal.markNotification", "work.inbox"],
  ["work.personal.search", "work.search"],
  ["work.personal.savedSearches", "work.saved_searches"],
  ["work.personal.saveSearch", "work.saved_searches"],
  ["work.personal.deleteSearch", "work.saved_searches"],
  ["work.forms.", "work.forms"],
  ["work.rules.", "work.rules"],
  ["work.templates.", "work.templates"],
  ["work.bundles.", "work.bundles"],
  ["work.approvals.", "work.approvals"],
  ["work.goals.", "work.goals"],
  ["work.portfolios.", "work.portfolios"],
  ["work.statusUpdates.", "work.status_updates"],
  ["work.reporting.", "work.reporting_dashboards"],
  ["work.workload.upsert", "work.capacity_planning"],
  ["work.workload.", "work.workload"],
  ["work.budgets.", "work.budgets"],
  ["work.time.", "work.time_tracking"],
  ["work.gantt.", "work.views.gantt"],
  ["work.members.", "work.object_permissions"],
  ["portal.work.", "work.guests"],
  ["work.", "work.projects"],
  ["crm.", "crm.workspace"],
  ["deals.", "crm.workspace"],
  ["clients.", "crm.workspace"],
  ["scopes.", "crm.workspace"],
  ["leads.", "crm.workspace"],
  ["outreach.", "crm.workspace"],
  ["tasks.", "delivery.workspace"],
  ["briefs.", "delivery.workspace"],
  ["calendars.", "delivery.workspace"],
  ["assets.", "delivery.workspace"],
  ["invoices.", "finance.workspace"],
  ["vat.", "finance.workspace"],
  ["portal.", "portal.client"],
];

export function featureForTrpcPath(path: string): string | null {
  return API_FEATURES.find(([prefix]) => path.startsWith(prefix))?.[1] ?? null;
}
